### ISSUE TITLE
ImportError: no module named 'turtle'

### ISSUE THREAD

**Issue by anandakrishnas** [omarKmekkawy/Interfacing-Laptop-Battery-With-RaspberryPi#1]
I tried all but still getting error as 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
**ImportError: no module named 'turtle'**

can you share the turtle file? or link?

**Comment by omarKmekkawy** [comment]
Try to use "Python3.7" and it will work fine with you. Give a try and tell me.
